# Generated by Django 6.0.5 on 2026-05-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
