# Generated by Django 6.0.5 on 2026-05-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_activity_predicted_cost_trip_predicted_total_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="duration_minutes",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="activity",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
